### ISSUE TITLE
Gated resource links within content should be ungated when cookie is set

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1143] opened 2023-08-29 13:13 UTC
If a link to the gated resource is present within the content and a cookie is set, the resource should be ungated for that user. 

Example - https://1104--moleculardevices--hlxsites.hlx.page/lab-notes/cellular-imaging-systems/case-study-assay-ready-patient-derived-organoids-and-high-throughput-3d-imaging
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/f4e212b6-1091-4c9b-b6ca-06a267ad33dc)

**Comment by mhaack** [comment] 2023-08-30 08:40
@alexcarol @duynguyen @alinarublea lets this discuss this in a quick sync. This is more tricky as @duynguyen wrote the links are in the content and we would need to scan theoretically all links etc.

**Comment by alexcarol** [comment] 2023-08-30 08:43
Rather than change the links, could we add logic on the gated pages to redirect if the cookie is set? Is there any reason why we're not doing that at the moment?

**Comment by alexcarol** [comment] 2023-08-30 09:02
> The gate pages don't now the ungatted page, it is the other way arround.
Even if they "don't know it", we're going to need some logic that finds the gated page based on the url (either as a link or in the page itself), so it doesn't look like we can't get around it. That said, rather than update the DOM, wouldn't it be simpler to redirect to the gated version if you should have access to it? (regardless of how you got there)

**Comment by duynguyen** [comment] 2023-08-31 10:01
@alexcarol FYI ☝️

**Comment by alexcarol** [comment] 2023-08-31 12:25
@MeghnaTewari I'm trying to find the ungated version for the page linked in  https://1104--moleculardevices--hlxsites.hlx.page/lab-notes/cellular-imaging-systems/case-study-assay-ready-patient-derived-organoids-and-high-throughput-3d-imaging (the gated page is https://1104--moleculardevices--hlxsites.hlx.page/en/assets/ebook/dd/img/essential-guide-to-organoids-in-drug-discovery if i'm not mistaken), but I can't find the ungated version, does it still exist?

**Comment by MeghnaTewari** [comment] 2023-08-31 12:28
@alexcarol here is the ungated ebook pdf https://www.moleculardevices.com/sites/default/files/en/assets/ebook/dd/img/essential-guide-to-organoids-in-drug-discovery.pdf

**Comment by alexcarol** [comment] 2023-09-01 07:18
@MeghnaTewari the issue is fixed in this branch, could you test it? https://issue-1143--moleculardevices--hlxsites.hlx.page

Note: the way it's solved is by making it so that when you enter a landing gated page you'll be redirected to the ungated version when the cookie is set. This does make it a bit tricky to test it, as in many cases the link takes you to the production site. In that case you will need to update the url manually on the browser with https://issue-1143--moleculardevices--hlxsites.hlx.page to be able to test it in this branch. Let me know if you have any questions.

**Comment by MeghnaTewari** [comment] 2023-09-01 08:09
@alexcarol Verfied. It looks good.

**Closed** 2023-09-01 08:53 UTC
