### ISSUE TITLE
Lost 'speak to specialist' and 'demo' tracking

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1080] opened 2023-08-18 07:00 UTC
Please fix this customer reported issue 

Hi,

At the start of the year, we implemented tracking for each call to action for example any 'speak to specialist' CTA will go to the thank you page with its own URL parameter. Same with 'demo' cta and 'quote request' cta. They go to thank you pages with URL parameters like 'rfq=Call' and 'rfq=Demo' and it was working perfectly fine until now.

Now I see that all CTA conversions lead to thank you page with the URL parameter -'rfq=Quote' I cannot identify which conversion is coming from which CTA button

This impacts PPC machine learning for conversions, and I am sure this has an organic impact too tracking and segmenting conversions.

Any idea how this happened?

Here are the screenshots of TY pages after submitting the form through 'speak to specialist CTA and demo CTA

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/a0e841cf-b17e-4913-a02c-e0fa9bf39b92)

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b626536b-b02c-45b1-b3dd-3d5cd0e67228)

**Comment by lydiapuric** [comment] 2023-08-18 11:20
@MeghnaTewari Next to 'quote' cta, you mention 'demo' cta and 'quote request' cta. They go to thank you pages with URL parameters like 'rfq=Call' and 'rfq=Demo'.  
Questions: 
1. Are there other types?
2. How to differentiate what type needs to be sent with the `rfq` parameter when clicking the CTA button?

**Comment by MeghnaTewari** [comment] 2023-08-18 11:39
@lydiapuric Let's connect quickly for this if you are available?

**Comment by MeghnaTewari** [comment] 2023-08-18 12:03
Giving example from the old site
https://live-md30.pantheonsite.io/products/microplate-readers

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/415851a8-d56c-4396-9688-aea709bf6791)
Please check the behavior here

1. For speak to a specialist CTA, it should have ?request_type=Call in the URL

https://live-md30.pantheonsite.io/quote-request?request_type=Call&cid=12

2. For request a demo it should have ?request_type=Demo in the URL

https://live-md30.pantheonsite.io/quote-request?request_type=Demo&cid=12


Now for TY page, for both call and demo URLs-

1. When you submit the form without clicking on this checkbox, the URL should have these parameters as well ( subscribe=false ) 

https://live-md30.pantheonsite.io/quote-request-success?cid=12&rfq=Demo&subscribe=false
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/e4727a4a-40ba-45c5-98e7-d64590d0962d)

2. When you submit the form with the checkbox, the URL should be ( subscribe=true ) 
https://live-md30.pantheonsite.io/quote-request-success?cid=12&rfq=Demo&subscribe=true

**Comment by MeghnaTewari** [comment] 2023-08-18 12:05
> 1. Are there other types?


No other types

**Comment by MeghnaTewari** [comment] 2023-08-21 06:59
@andreituicu @lydiapuric Please let us know when this is fixed. This is a high priority issue as well.

**Comment by lydiapuric** [comment] 2023-08-21 07:23
I will start working on this today.

**Comment by mhaack** [comment] 2023-08-21 07:44
@MeghnaTewari @dev-rajneeshkumar @kapildhiman this was communicated that this is not used any more, hence this was not implemented by Kapil!

**Comment by dev-rajneeshkumar** [comment] 2023-08-21 07:53
@mhaack  I don't think so that we have suggested anything like for these buttons as these are important part of the RFQ functionality .  And eventually as we say that import is done for the content as it is which is visible on the page so it was part of meta data and link only. Please correct me if I am wrong here.

**Comment by lydiapuric** [comment] 2023-08-21 10:10
@MeghnaTewari Can you please confirm that these pages are already in a correct status?
https://www.moleculardevices.com/products/3d-biology

Regarding TY page, see #1084
This form is an embedded iframe from HubSpot. The Franklin page doesn't control the behavior.
The MolDev team has already opened discussion threads with hubspot teams.
@dev-rajneeshkumar Are these parameters already discussed or addressed with the HubSpot team?

**Comment by MeghnaTewari** [comment] 2023-08-21 10:47
@lydiapuric Yes, "Speak to a specialist" and "Request a demo" CTA URLs are fine on this page.

I submitted the rfq for the Demo URL, please see the difference in **Thank You URL** 

https://www.moleculardevices.com/quote-request-success?cat=3D%20Biology&cmp=70170000000hlRaAAI&rfq=Quote&subscribe=false

https://live-md30.pantheonsite.io/quote-request-success?cid=1041&rfq=Demo&subscribe=false

1. there is a % in between 3d biology
2. cmp id was not there on the old live 
3. rfq=Demo is missing in the TY URL

**Comment by mhaack** [comment] 2023-08-21 11:33
@MeghnaTewari can you move "Another thing I noticed, on the below pages, the link for these 2 buttons are not going to their pid in the RFQ. They are going to the global RFQ." with the URLs to another issue please. These is a content issue, docs don't have a family id. Please assign the new issue to me.

**Comment by mhaack** [comment] 2023-08-21 11:36
> I don't think so that we have suggested anything like for these buttons as these are important part of the RFQ functionality . And eventually as we say that import is done for the content as it is which is visible on the page so it was part of meta data and link only. Please correct me if I am wrong here.

See https://adobe-dx-support.slack.com/archives/C04QNDDUADT/p1683897900956719?thread_ts=1683879841.066689&cid=C04QNDDUADT

I explicitly asked for the call/demo value in the parameter and we got a "remove this" as answer.

**Comment by MeghnaTewari** [comment] 2023-08-21 11:38
@mhaack Sure. Here you go https://github.com/hlxsites/moleculardevices/issues/1093
Don't have permission to assign in GH I think.

**Comment by dev-rajneeshkumar** [comment] 2023-08-21 11:43
> 

Yes @mhaack  I can see that. Let me reach out Kapil that why he has suggested this to remove.

**Comment by dev-rajneeshkumar** [comment] 2023-08-21 11:58
@mhaack As I can see request_type=Demo is already implemented on the 2nd button so similarly  request_type=Call is required on first button. I hope this is a common section so if can be implemented quickly then please add as it is anyhow needed because business managers use this as an identifier for their campaigns. 

![image](https://github.com/hlxsites/moleculardevices/assets/42608830/0cdbf711-b7e0-425e-92ef-7c1a6d8ef5bd)

Regards,
Rajneesh

**Comment by mhaack** [comment] 2023-08-21 15:47
> @mhaack As I can see request_type=Demo is already implemented on the 2nd button so similarly request_type=Call is required on first button. I hope this is a common section so if can be implemented quickly then please add as it is anyhow needed because business managers use this as an identifier for their campaigns.

This is "by accident"! `request_type=Call` is removed by the import script explicitly after it was confirmed as un-used by @kapildhiman . All other request_type parameters are imported and not touched by the import script.

However in the code for the request-quote is nothing which handles `request_type=` parameter at all?

**Comment by mhaack** [comment] 2023-08-22 14:55
The coding part has been fixed via https://github.com/hlxsites/moleculardevices/pull/1100. Keeping this open for the content fixes

**Closed** 2023-08-23 12:21 UTC
Labels: frontend, content, customer reported, P2
