### ISSUE TITLE
Filter issue in search

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1138] opened 2023-08-29 06:53 UTC
**Please look into this customer reported issue we received -** 

I’m having a search issue that I’m wondering if anyone else is experiencing.

My newer app notes don’t seem to be appearing in the Resources/App Notes default results.

If you just refine by “Application Note and Cellular Imaging” and sort by date, the most recent app note available is from 2022.
 
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/3d16d03f-c8b1-4035-8fd8-059e0ee72574)

If I search for a new app note by name, in this case, “Neural outgrowth analysis”  it does come up in the search and is properly tagged and available on the IXMC & IN Carta product pages, so I’m not sure why it’s not in the “Application Note and Cellular Imaging” filter-only search.
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/b0d779a9-33df-4e17-bf15-28f6c4325a9a)

**Comment by mhaack** [comment] 2023-08-29 07:53
I think the issue us the App Note is Coveo is not recognized as App Note. Hence it not shows up in the filters. Also the icon is wrong.

**Comment by MeghnaTewari** [comment] 2023-08-29 07:59
@mhaack  The app note filter is working fine, I  am able to see the mentioned app note when I select that filter

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/e4ea32d8-3b84-47fc-9b13-63fe076a8df2)
https://www.moleculardevices.com/en/assets/app-note/dd/img/neural-outgrowth-analysis-3d-human-brain-micro-tissues-for-compound-screening-applications

But when I select the product category for that app note ( which is Cellular Imaging Systems), the latest app notes are not visible

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/ebb43508-13df-45c5-ba8e-4c0b2ef4e487)

**Comment by MeghnaTewari** [comment] 2023-08-29 08:02
Yes the app note icon is not consistent, for some It shows the correct icon but for some it shows the general document icon 

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/1632911a-b077-4337-8014-f8f23cdb1586)

**Comment by mhaack** [comment] 2023-08-29 08:08
Yes you are right, I checked on Coveo, it was indexed with "App Note" but wrong icon and missing categories. That is the root cause. I checked our data we provided to Coveo, that is correct. Lets wait until the re-index is done.

**Comment by mhaack** [comment] 2023-08-29 09:12
@MeghnaTewari fixed both:
* original issue about the one app note not showing up in the filters
* additionally app note icons should be fixed as well

**Comment by mhaack** [comment] 2023-08-29 12:41
Closing as confirmed by @MeghnaTewari

**Closed by mhaack** 2023-08-29 12:41 UTC
Labels: content, customer reported
