### ISSUE TITLE
SEMrush Error report - Duplicate title tag and meta description

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1048] opened 2023-08-10 08:11 UTC
Can you please look into this SEMrush Duplicate Title Tag issue - https://www.semrush.com/siteaudit/campaign/2056263/review/#issue/detail/6
 
It appears that a directory called “/fragments/…” was created that maybe highlighting certain sections and topic cards that are embedded throughout the section
 
We also have duplicate meta description errors that need to be corrected.

Please work with Raj to review along with the Google Search Console errors. It seems that Google is cracking down on these duplicate issues … can you please ask him if he’s seeing similar trends.

currently show 94 duplicate title tags and 63 duplicate meta descriptions
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/4e2d6e41-5179-4549-88ab-8a02b92af7e9)

**Comment by andreituicu** [comment] 2023-08-10 08:59
We should check if for `/fragments/**` the `robots` is correctly configured to not allow indexing. I think this should make google happy, because it would only index the page, not the fragment.

@MeghnaTewari @dev-rajneeshkumar could we also get access to check the report?

**Comment by andreituicu** [comment] 2023-08-10 09:15
@duynguyen just checking with you, because maybe you have past experience from other projects with this
https://github.com/hlxsites/moleculardevices/blob/main/robots.txt allows access on the whole website. The fragments are not specifically referenced in the sitemap, but they will be discovered by crawlers because they are included in the markup of pages.

What  I am thinking is that we could use the bulk metadata `metadata.xls` to set
`/fragments/**` with `robots` : `noindex`
`/drafts/**` with `robots`: `noindex,nofollow`

Does this sound like a good plan?

**Comment by duynguyen** [comment] 2023-08-10 09:50
@andreituicu I would do the same. shall we cross check in franklin-chat?

**Comment by andreituicu** [comment] 2023-08-10 13:06
Cross checked with other projects and the google docs https://developers.google.com/search/docs/crawling-indexing/block-indexing . I've set the metadata accordingly in `metadata.xml` and published.

Can you please ask Graciela to re-execute the scan and confirm this fixes the errors? Thank you!

**Comment by andreituicu** [comment] 2023-08-14 13:46
@MeghnaTewari @dev-rajneeshkumar can we close this? is it confirmed that the problem was solved?

**Comment by andreituicu** [comment] 2023-08-22 09:21
No feedback in 1 week. Assuming it worked as expected. Can be reopened if it is still an issue. CC @mhaack  @MeghnaTewari @dev-rajneeshkumar

**Comment by dev-rajneeshkumar** [comment] 2023-08-22 11:46
@andreituicu /fragments urls are still there in the report so reopening this issue.

**Comment by mhaack** [comment] 2023-08-24 07:40
Ask discussed with @dev-rajneeshkumar & Raj this is fixed

**Closed by mhaack** 2023-08-24 07:40 UTC
Labels: performance, customer reported, P3
