### ISSUE TITLE
The product finder is using shared data for front and backend operations

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#1113] opened 2023-08-24 05:26 UTC
The product finder is still using shared data for front and backend operations. Ideally, this should be split. Categories in step 2 cannot be translated without breaking functionality.

On step three no products are displayed. This appears to be caused by another mismatch between translated and untranslated data.

In /blocks/product-finder/product-finder.js

async function stepThree(e) {
…
let category = getTabTitle(e.target);
const originalCategory = category;
…
const categoryData = categories.find(
  (c) => c.category === originalCategory && c.type === originalType,
);

The “category” value retrieved from the “getTabTitle” function is translated. Later on this value is compared to categories directly from the json, which is untranslated. In order for the last step to work the tab title (data-title attribute) should be in English while the displayed text (span.icon-title) is translated.

**Note: This is an issue pointed out by Transperfect and needs to be fixed by Adobe Team.**

**Comment by jose-correia** [comment] 2023-08-24 14:34
@MeghnaTewari Can you confirm that the issue is still happening? We don't see any translation issues on our side, and the product-finder works normally in the alternative language websites

**Comment by mhaack** [comment] 2023-08-24 15:35
Test with this URL https://dede-hlxsites-moleculardevices.onelink-translations.com/product-finder

**Comment by MeghnaTewari** [comment] 2023-08-29 06:19
@mhaack just checked with this URL and found a couple of UI issues
https://dede-hlxsites-moleculardevices.onelink-translations.com/product-finder

1.  Please align the arrow icon and the compare checkbox
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/98e92ea2-2144-4580-8e95-4f134d46ab32)

2.< br > tag on some places

![image](https://github.com/hlxsites/moleculardevices/assets/138755144/1dbdce19-f88d-4e31-a5ce-cb8b6ebc2de9)

**Comment by mhaack** [comment] 2023-08-29 06:59
@jose-correia can you look into the compare box issue (1) in the comment from @MeghnaTewari 

@MeghnaTewari (2) is a known issue see https://github.com/hlxsites/moleculardevices/issues/927 and must be fixed by Transperfect

**Comment by mhaack** [comment] 2023-08-29 16:43
Re-open for style fixes

**Comment by MeghnaTewari** [comment] 2023-09-01 04:32
@jose-correia  any update on the compare box issue?

**Comment by alexcarol** [comment] 2023-09-01 09:09
> @jose-correia any update on the compare box issue?

@MeghnaTewari Have you checked the behaviour in production? It looks like it displays correctly there, could you confirm it's the desired behaviour?
https://de.moleculardevices.com/product-finder

![image](https://github.com/hlxsites/moleculardevices/assets/1713440/99f9fb7c-08d1-4950-be42-b0edb5a278cd)

**Comment by MeghnaTewari** [comment] 2023-09-01 09:32
@alexcarol  Just checked with this URL, and it looks fine. https://de.moleculardevices.com/product-finder

**Comment by mhaack** [comment] 2023-09-01 09:57
https://de.moleculardevices.com/product-finder is the old URL, you need to check https://dede-hlxsites-moleculardevices.onelink-translations.com/product-finder

**Comment by MeghnaTewari** [comment] 2023-09-01 11:07
oh, yes....I see issue on this https://dede-hlxsites-moleculardevices.onelink-translations.com/product-finder
![image](https://github.com/hlxsites/moleculardevices/assets/138755144/6e0a2e88-5fd5-4123-a94a-1a040d689972)

**Comment by alexcarol** [comment] 2023-09-01 16:06
@MeghnaTewari can you check this PR? https://github.com/hlxsites/moleculardevices/pull/1159 it can be tested for german using this branch: https://issue-1113-de--moleculardevices--hlxsites.hlx.page/product-finder (and for english with this one https://issue-1113--moleculardevices--hlxsites.hlx.page/product-finder)

**Closed** 2023-09-01 16:23 UTC
Labels: customer reported, external, P3
