### ISSUE TITLE
[Applications] Large subtitles

### ISSUE THREAD

**Issue by MeghnaTewari** [hlxsites/moleculardevices#840] opened 2023-07-06 08:14 UTC
Reduce the font size for subtitles on all the application pages.
Example URLs-

https://franklin.moleculardevices.com/applications/3d-cell-models
https://franklin.moleculardevices.com/applications/organoid-innovation-center
https://franklin.moleculardevices.com/applications/cancer-research
https://franklin.moleculardevices.com/applications/cell-imaging/cell-painting

**Comment by duynguyen** [comment] 2023-07-06 08:46
@MeghnaTewari I couldn't find which subtitle you referred to. Can you make a screenshot?

**Comment by MeghnaTewari** [comment] 2023-07-06 10:17
@duynguyen  this one
![image ](https://github.com/hlxsites/moleculardevices/assets/138755144/afa1d2bb-e2d2-4799-9133-43864f7f29f2)

**Comment by duynguyen** [comment] 2023-07-06 13:42
Root cause: Subtitles are imported as H2.
Solution: update them to normal text.

**Comment by duynguyen** [comment] 2023-07-13 14:17
@MeghnaTewari fixed on all application pages. could you please verify?

**Closed by duynguyen** 2023-07-13 14:17 UTC
